services:
  # app:
  #   build: .
  #   command: sh -c "npm i && npm run start"
  #   ports:
  #     - ${PORT}:${PORT}
  #   working_dir: /todo-app
  #   volumes:
  #     - .:/todo-app
  #   depends_on:
  #     - postgres
  #   environment:
  #     PORT: 5000
  #     POSTGRES_USER: fiqri
  #     POSTGRES_PASSWORD: mantap
  #     POSTGRES_DB: todoapp
  #     DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      
  postgres:
    image: postgres
    restart: always
    hostname: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres: